export const RUTAS_POR_ROL = {
  aprendiz: [
    '/aprendiz/dashboard',
    '/aprendiz/propuestas',
    '/aprendiz/ficha',
    '/aprendiz/similitudes',
    '/aprendiz/alertas',
    '/aprendiz/reportar-falla',
    '/aprendiz/perfil',
    '/aprendiz/detalle-proyecto/4',
    '/aprendiz/detalle-proyecto/1',
    '/aprendiz/detalle-ficha/1',
    '/aprendiz/detalle-similitud/1',
    '/aprendiz/perfil-companero/5',
    '/aprendiz/perfil-instructor',
    '/aprendiz/resultado-analisis?analisis=ok',
  ],
  instructor: [
    '/instructor/dashboard',
    '/instructor/revision-propuestas',
    '/instructor/similitudes',
    '/instructor/fichas',
    '/instructor/detalle-ficha/1',
    '/instructor/directorio-ficha/1',
    '/instructor/detalle-proyecto/4',
    '/instructor/detalle-similitud/1',
    '/instructor/alertas',
    '/instructor/reportar-falla',
    '/instructor/perfil',
    '/instructor/perfil-companero/5',
  ],
  admin: [
    '/admin/dashboard',
    '/admin/usuarios',
    '/admin/proyectos',
    '/admin/detalle-proyecto/4',
    '/admin/similitudes',
    '/admin/detalle-similitud/1',
    '/admin/detalle-usuario/2',
    '/admin/reportes-fallas',
    '/admin/detalle-reporte/1',
    '/admin/notificaciones',
    '/admin/bitacora',
    '/admin/config-similitud',
    '/admin/perfil',
  ],
}

export const RUTAS_PUBLICAS = [
  '/',
  '/login',
  '/register',
  '/recuperar-contrasena',
  '/restablecer-contrasena',
  '/confirmacion',
]
